# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launcher_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(395, 316)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 377, 278))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.resolutionLabel = QtWidgets.QLabel(self.layoutWidget)
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.verticalLayout_2.addWidget(self.resolutionLabel)
        self.resolutionList = QtWidgets.QListWidget(self.layoutWidget)
        self.resolutionList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resolutionList.setObjectName("resolutionList")
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resolutionList.addItem(item)
        self.verticalLayout_2.addWidget(self.resolutionList)
        self.figureLabel = QtWidgets.QLabel(self.layoutWidget)
        self.figureLabel.setObjectName("figureLabel")
        self.verticalLayout_2.addWidget(self.figureLabel)
        self.figureList = QtWidgets.QListWidget(self.layoutWidget)
        self.figureList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.figureList.setObjectName("figureList")
        item = QtWidgets.QListWidgetItem()
        self.figureList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.figureList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.figureList.addItem(item)
        self.verticalLayout_2.addWidget(self.figureList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.colorLabel = QtWidgets.QLabel(self.layoutWidget)
        self.colorLabel.setObjectName("colorLabel")
        self.verticalLayout.addWidget(self.colorLabel)
        self.blackRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.blackRadio.setEnabled(True)
        self.blackRadio.setChecked(True)
        self.blackRadio.setObjectName("blackRadio")
        self.verticalLayout.addWidget(self.blackRadio)
        self.redRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.redRadio.setObjectName("redRadio")
        self.verticalLayout.addWidget(self.redRadio)
        self.greenRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.greenRadio.setObjectName("greenRadio")
        self.verticalLayout.addWidget(self.greenRadio)
        self.blueRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.blueRadio.setObjectName("blueRadio")
        self.verticalLayout.addWidget(self.blueRadio)
        self.sizeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.sizeLabel.setObjectName("sizeLabel")
        self.verticalLayout.addWidget(self.sizeLabel)
        self.sizeSpinbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.sizeSpinbox.setMaximum(100)
        self.sizeSpinbox.setProperty("value", 10)
        self.sizeSpinbox.setObjectName("sizeSpinbox")
        self.verticalLayout.addWidget(self.sizeSpinbox)
        self.speedLabel = QtWidgets.QLabel(self.layoutWidget)
        self.speedLabel.setObjectName("speedLabel")
        self.verticalLayout.addWidget(self.speedLabel)
        self.speedSpinbox = QtWidgets.QSpinBox(self.layoutWidget)
        self.speedSpinbox.setProperty("value", 10)
        self.speedSpinbox.setObjectName("speedSpinbox")
        self.verticalLayout.addWidget(self.speedSpinbox)
        self.launchButton = QtWidgets.QPushButton(self.layoutWidget)
        self.launchButton.setObjectName("launchButton")
        self.verticalLayout.addWidget(self.launchButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.resolutionList.setCurrentRow(0)
        self.figureList.setCurrentRow(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Celldiv Launcher"))
        self.resolutionLabel.setText(_translate("MainWindow", "Resolution"))
        __sortingEnabled = self.resolutionList.isSortingEnabled()
        self.resolutionList.setSortingEnabled(False)
        item = self.resolutionList.item(0)
        item.setText(_translate("MainWindow", "500x500"))
        item = self.resolutionList.item(1)
        item.setText(_translate("MainWindow", "600x600"))
        item = self.resolutionList.item(2)
        item.setText(_translate("MainWindow", "700x700"))
        item = self.resolutionList.item(3)
        item.setText(_translate("MainWindow", "800x800"))
        item = self.resolutionList.item(4)
        item.setText(_translate("MainWindow", "900x900"))
        item = self.resolutionList.item(5)
        item.setText(_translate("MainWindow", "1000x1000"))
        self.resolutionList.setSortingEnabled(__sortingEnabled)
        self.figureLabel.setText(_translate("MainWindow", "Figure"))
        __sortingEnabled = self.figureList.isSortingEnabled()
        self.figureList.setSortingEnabled(False)
        item = self.figureList.item(0)
        item.setText(_translate("MainWindow", "Random"))
        item = self.figureList.item(1)
        item.setText(_translate("MainWindow", "Glider"))
        item = self.figureList.item(2)
        item.setText(_translate("MainWindow", "Gun"))
        self.figureList.setSortingEnabled(__sortingEnabled)
        self.colorLabel.setText(_translate("MainWindow", "Cell color"))
        self.blackRadio.setText(_translate("MainWindow", "Black"))
        self.redRadio.setText(_translate("MainWindow", "Red"))
        self.greenRadio.setText(_translate("MainWindow", "Green"))
        self.blueRadio.setText(_translate("MainWindow", "Blue"))
        self.sizeLabel.setText(_translate("MainWindow", "Cell size"))
        self.speedLabel.setText(_translate("MainWindow", "Game speed"))
        self.launchButton.setText(_translate("MainWindow", "Launch"))
